services:
  - type: web
    name: trustmart-backend
    env: node
    region: singapore
    rootDir: server
    buildCommand: npm install
    startCommand: npx prisma db push --accept-data-loss && node seed.js && node index.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: trustmart-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production

databases:
  - name: trustmart-db
    databaseName: trustmart
    user: trustmart
    region: singapore
