services:
  - type: web
    name: liyztit-backend
    env: node
    region: singapore
    rootDir: server
    buildCommand: npm install
    startCommand: npx prisma migrate deploy && node seed.js && node index.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: liyztit-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production

databases:
  - name: liyztit-db
    databaseName: liyztit
    user: liyztit
    region: singapore
