services:
  - type: web
    name: liyztit-backend
    env: node
    region: singapore
    rootDir: server
    buildCommand: npm install && npx prisma generate && node seed.js
    startCommand: node index.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: liyztit-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5001

databases:
  - name: liyztit-db
    databaseName: liyztit
    user: liyztit
    region: singapore
